version: '3'
services:
  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env
    volumes:
      - ./Backend:/app
    # restart: always

  frontend:
    build: ./Frontend/my-react-app
    ports:
      - "5173:5173"
    # restart: always
